poincare_portrait:
  z_min: 0.1
  z_max: 3.0
  z_step: 0.05
  z_dot_min: 0.0
  z_dot_max: 0.1
  z_dot_step: 0.2
  eccentricity: 0.1
  periods: 5.0
initial_values:
  z_start: 1.0
  z_dot_start: 0
  eccentricity: 0.1
  periods: 5.0
solver_params:
  time_delta: 0.001
  skip_n_outs: 10
